[package]
authors = ["Tnze"]
default-run = "app"
description = "BestCraft rust backend"
edition = "2021"
license = ""
name = "app"
repository = ""
rust-version = "1.57"
version = "0.2.11"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = {version = "1.0.0-rc.7", features = [] }

[dependencies]
csv = "1.1.6"
ffxiv-crafting = {version = "6.0.12", features = ["serde-support"] }
msgbox = "0.7.0"
rayon = "1.5.2"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = {version = "1.0.0-rc.8", features = ["api-all", "updater"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
lto = true
