[package]
authors = ["Tnze"]
default-run = "app"
description = "BestCraft rust backend"
edition = "2021"
license = ""
name = "app"
repository = ""
rust-version = "1.57"
version = "0.5.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.1", features = [] }

[dependencies]
axum = "0.5"
ffxiv-crafting = { version = "6.0.12", features = ["serde-support"] }
futures = "0.3"
msgbox = "0.7.0"
rayon = "1.5.3"
sea-orm = { version = "0.9", features = [
    "sqlx-sqlite",
    "runtime-tokio-native-tls",
    "macros",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "1.1", features = ["api-all", "updater"] }
tokio = "1.20"
anyhow = "1.0.65"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
lto = true
