// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
}
export {}
