// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Action: typeof import('./src/components/designer/Action.vue')['default']
    ActionPanel: typeof import('./src/components/designer/ActionPanel.vue')['default']
    Condition: typeof import('./src/components/designer/Condition.vue')['default']
    Designer: typeof import('./src/components/designer/Designer.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Gearsets: typeof import('./src/components/Gearsets.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Recipe: typeof import('./src/components/Recipe.vue')['default']
    Split: typeof import('./src/components/designer/Split.vue')['default']
  }
}

export { }
