// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Action: typeof import('./src/components/designer/Action.vue')['default']
    ActionPanel: typeof import('./src/components/designer/ActionPanel.vue')['default']
    ActionQueue: typeof import('./src/components/designer/ActionQueue.vue')['default']
    Condition: typeof import('./src/components/designer/Condition.vue')['default']
    Designer: typeof import('./src/components/designer/Designer.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    Gearsets: typeof import('./src/components/Gearsets.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Recipe: typeof import('./src/components/Recipe.vue')['default']
    RecipePanel: typeof import('./src/components/RecipePanel.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    Split: typeof import('./src/components/designer/Split.vue')['default']
    StatusBar: typeof import('./src/components/designer/StatusBar.vue')['default']
  }
}

export { }
