//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "Items")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "Name", column_type = "custom(\"LONGTEXT\")")]
    pub name: String,
    #[sea_orm(column_name = "Level")]
    pub level: u32,
    #[sea_orm(column_name = "CanBeHQ")]
    pub can_be_hq: i8,
    #[sea_orm(column_name = "ItemUICategoryId")]
    pub item_ui_category_id: Option<u32>,
    #[sea_orm(column_name = "ItemSearchCategoryId")]
    pub item_search_category_id: Option<u32>,
    #[sea_orm(column_name = "ItemActionId")]
    pub item_action_id: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::item_action::Entity",
        from = "Column::ItemActionId",
        to = "super::item_action::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemAction,
    #[sea_orm(
        belongs_to = "super::item_search_categories::Entity",
        from = "Column::ItemSearchCategoryId",
        to = "super::item_search_categories::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemSearchCategories,
    #[sea_orm(
        belongs_to = "super::item_ui_categories::Entity",
        from = "Column::ItemUiCategoryId",
        to = "super::item_ui_categories::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ItemUiCategories,
    #[sea_orm(has_many = "super::item_with_amount::Entity")]
    ItemWithAmount,
}

impl Related<super::item_action::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemAction.def()
    }
}

impl Related<super::item_search_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemSearchCategories.def()
    }
}

impl Related<super::item_ui_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemUiCategories.def()
    }
}

impl Related<super::item_with_amount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemWithAmount.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
