//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "RecipeLevelTables")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "ClassJobLevel")]
    pub class_job_level: u8,
    #[sea_orm(column_name = "SuggestedCraftsmanship")]
    pub suggested_craftsmanship: u16,
    #[sea_orm(column_name = "Difficulty")]
    pub difficulty: u16,
    #[sea_orm(column_name = "Quality")]
    pub quality: u32,
    #[sea_orm(column_name = "ProgressDivider")]
    pub progress_divider: u8,
    #[sea_orm(column_name = "QualityDivider")]
    pub quality_divider: u8,
    #[sea_orm(column_name = "ProgressModifier")]
    pub progress_modifier: u8,
    #[sea_orm(column_name = "QualityModifier")]
    pub quality_modifier: u8,
    #[sea_orm(column_name = "Durability")]
    pub durability: u16,
    #[sea_orm(column_name = "ConditionsFlag")]
    pub conditions_flag: u16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recipes::Entity")]
    Recipes,
}

impl Related<super::recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
