//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "WKSMissionRecipe")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "Recipe0Id")]
    pub recipe0_id: Option<u32>,
    #[sea_orm(column_name = "Recipe1Id")]
    pub recipe1_id: Option<u32>,
    #[sea_orm(column_name = "Recipe2Id")]
    pub recipe2_id: Option<u32>,
    #[sea_orm(column_name = "Recipe3Id")]
    pub recipe3_id: Option<u32>,
    #[sea_orm(column_name = "Recipe4Id")]
    pub recipe4_id: Option<u32>,
    #[sea_orm(column_name = "IsExpert")]
    pub is_expert: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::recipes::Entity",
        from = "Column::Recipe0Id",
        to = "super::recipes::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Recipes5,
    #[sea_orm(
        belongs_to = "super::recipes::Entity",
        from = "Column::Recipe1Id",
        to = "super::recipes::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Recipes4,
    #[sea_orm(
        belongs_to = "super::recipes::Entity",
        from = "Column::Recipe2Id",
        to = "super::recipes::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Recipes3,
    #[sea_orm(
        belongs_to = "super::recipes::Entity",
        from = "Column::Recipe3Id",
        to = "super::recipes::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Recipes2,
    #[sea_orm(
        belongs_to = "super::recipes::Entity",
        from = "Column::Recipe4Id",
        to = "super::recipes::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Recipes1,
    #[sea_orm(has_many = "super::wks_mission_unit::Entity")]
    WksMissionUnit,
}

impl Related<super::wks_mission_unit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WksMissionUnit.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
