//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "WKSMissionUnit")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "Name", column_type = "custom(\"LONGTEXT\")")]
    pub name: String,
    #[sea_orm(column_name = "RecipeId")]
    pub recipe_id: Option<u32>,
    #[sea_orm(column_name = "ToDo0Id")]
    pub to_do0_id: Option<u32>,
    #[sea_orm(column_name = "ToDo1Id")]
    pub to_do1_id: Option<u32>,
    #[sea_orm(column_name = "ToDo2Id")]
    pub to_do2_id: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wks_mission_recipe::Entity",
        from = "Column::RecipeId",
        to = "super::wks_mission_recipe::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    WksMissionRecipe,
    #[sea_orm(
        belongs_to = "super::wks_mission_to_do::Entity",
        from = "Column::ToDo0Id",
        to = "super::wks_mission_to_do::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    WksMissionToDo3,
    #[sea_orm(
        belongs_to = "super::wks_mission_to_do::Entity",
        from = "Column::ToDo1Id",
        to = "super::wks_mission_to_do::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    WksMissionToDo2,
    #[sea_orm(
        belongs_to = "super::wks_mission_to_do::Entity",
        from = "Column::ToDo2Id",
        to = "super::wks_mission_to_do::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    WksMissionToDo1,
}

impl Related<super::wks_mission_recipe::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WksMissionRecipe.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
