//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub mod prelude;

pub mod collectables_shop_refine;
pub mod craft_types;
pub mod item_action;
pub mod item_food;
pub mod item_food_effect;
pub mod item_search_categories;
pub mod item_ui_categories;
pub mod item_with_amount;
pub mod items;
pub mod recipe_level_tables;
pub mod recipes;
