//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod categories;
pub mod craft_types;
pub mod item_with_amount;
pub mod items;
pub mod recipe_level_tables;
pub mod recipes;
