//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "itemfood")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::itemfoodeffect::Entity")]
    Itemfoodeffect,
}

impl Related<super::itemfoodeffect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Itemfoodeffect.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
