//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "ItemFood")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::item_food_effect::Entity")]
    ItemFoodEffect,
}

impl Related<super::item_food_effect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemFoodEffect.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
