//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "itemaction")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "Type")]
    pub r#type: u16,
    #[sea_orm(column_name = "Data1")]
    pub data1: u16,
    #[sea_orm(column_name = "Data2")]
    pub data2: u16,
    #[sea_orm(column_name = "Data3")]
    pub data3: u16,
    #[sea_orm(column_name = "Data4")]
    pub data4: u16,
    #[sea_orm(column_name = "Data5")]
    pub data5: u16,
    #[sea_orm(column_name = "Data6")]
    pub data6: u16,
    #[sea_orm(column_name = "Data7")]
    pub data7: u16,
    #[sea_orm(column_name = "Data8")]
    pub data8: u16,
    #[sea_orm(column_name = "DataHQ1")]
    pub data_hq1: u16,
    #[sea_orm(column_name = "DataHQ2")]
    pub data_hq2: u16,
    #[sea_orm(column_name = "DataHQ3")]
    pub data_hq3: u16,
    #[sea_orm(column_name = "DataHQ4")]
    pub data_hq4: u16,
    #[sea_orm(column_name = "DataHQ5")]
    pub data_hq5: u16,
    #[sea_orm(column_name = "DataHQ6")]
    pub data_hq6: u16,
    #[sea_orm(column_name = "DataHQ7")]
    pub data_hq7: u16,
    #[sea_orm(column_name = "DataHQ8")]
    pub data_hq8: u16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::items::Entity")]
    Items,
}

impl Related<super::items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Items.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
