//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "ItemFood")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "BaseParam1")]
    pub base_param1: u32,
    #[sea_orm(column_name = "Value1")]
    pub value1: i8,
    #[sea_orm(column_name = "Max1")]
    pub max1: i16,
    #[sea_orm(column_name = "ValueHQ1")]
    pub value_hq1: i8,
    #[sea_orm(column_name = "MaxHQ1")]
    pub max_hq1: i16,
    #[sea_orm(column_name = "BaseParam2")]
    pub base_param2: u32,
    #[sea_orm(column_name = "Value2")]
    pub value2: i8,
    #[sea_orm(column_name = "Max2")]
    pub max2: i16,
    #[sea_orm(column_name = "ValueHQ2")]
    pub value_hq2: i8,
    #[sea_orm(column_name = "MaxHQ2")]
    pub max_hq2: i16,
    #[sea_orm(column_name = "BaseParam3")]
    pub base_param3: u32,
    #[sea_orm(column_name = "Value3")]
    pub value3: i8,
    #[sea_orm(column_name = "Max3")]
    pub max3: i16,
    #[sea_orm(column_name = "ValueHQ3")]
    pub value_hq3: i8,
    #[sea_orm(column_name = "MaxHQ3")]
    pub max_hq3: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
