//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod categories;
pub mod craft_types;
pub mod item_with_amount;
pub mod items;
pub mod recipe_level_tables;
pub mod recipes;
