//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod crafttypes;
pub mod itemaction;
pub mod itemfood;
pub mod itemfoodeffect;
pub mod items;
pub mod itemsearchcategories;
pub mod itemuicategories;
pub mod itemwithamount;
pub mod recipeleveltables;
pub mod recipes;
