//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "recipes")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key)]
    pub id: u32,
    #[sea_orm(column_name = "Number")]
    pub number: i32,
    #[sea_orm(column_name = "CraftTypeId")]
    pub craft_type_id: u32,
    #[sea_orm(column_name = "RecipeLevelId")]
    pub recipe_level_id: u32,
    #[sea_orm(column_name = "ItemResultId")]
    pub item_result_id: u32,
    #[sea_orm(column_name = "MaterialQualityFactor")]
    pub material_quality_factor: u8,
    #[sea_orm(column_name = "DifficultyFactor")]
    pub difficulty_factor: u16,
    #[sea_orm(column_name = "QualityFactor")]
    pub quality_factor: u16,
    #[sea_orm(column_name = "DurabilityFactor")]
    pub durability_factor: u16,
    #[sea_orm(column_name = "RequiredCraftsmanship")]
    pub required_craftsmanship: u16,
    #[sea_orm(column_name = "RequiredControl")]
    pub required_control: u16,
    #[sea_orm(column_name = "CanHq")]
    pub can_hq: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::crafttypes::Entity",
        from = "Column::CraftTypeId",
        to = "super::crafttypes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Crafttypes,
    #[sea_orm(
        belongs_to = "super::itemwithamount::Entity",
        from = "Column::ItemResultId",
        to = "super::itemwithamount::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Itemwithamount,
    #[sea_orm(
        belongs_to = "super::recipeleveltables::Entity",
        from = "Column::RecipeLevelId",
        to = "super::recipeleveltables::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Recipeleveltables,
}

impl Related<super::crafttypes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Crafttypes.def()
    }
}

impl Related<super::itemwithamount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Itemwithamount.def()
    }
}

impl Related<super::recipeleveltables::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipeleveltables.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
